# Generated by Django 5.2.6 on 2025-10-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/', verbose_name='Картинка'),
        ),
    ]
